/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>

#include "greeter.h"
#include "sample.h"

using namespace coding_skill;

int main () {
    Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    std::cout << Sample::add(144, 111) << std::endl;
    return 0;
}
